indiv_zero = {
    'forca': {
        'agressividade': 0,
        'luta': 0,
        'resistencia': 0,
        'vigor': 0,
        'brutalidade': 0
    },
    'destreza': {
        'agilidade': 0,
        'proeficiencia': 0,
        'foco': 0,
        'equilibrio': 0,
        'reflexos': 0
    },
    'intelecto': {
        'conhecimentos': 0,
        'raclogico': 0,
        'controleemocional': 0,
        'curiosidade': 0,
        'inspecao': 0
    },
    'sabedoria': {
        'interpretacao': 0,
        'percepcao': 0,
        'tino': 0,
        'intuicao': 0,
        'empatia': 0
    },
    'carisma': {
        'aparencia': 0,
        'simpatia': 0,
        'socializacao': 0,
        'blefe': 0,
        'ego': 0
    },
    'sobrenatural': {
        'religiao': 0,
        'mediunidade': 0,
        'conhecocult': 0,
        'forcmental': 0,
        'clarividencia': 0
    }
}

map_names = {
    'forca': 'Força',
    'agressividade': 'Agressividade',
    'luta': 'Luta',
    'resistencia': 'Resistência',
    'vigor': 'Vigor',
    'brutalidade': 'Brutalidade',
    'destreza': 'Destreza',
    'agilidade': 'Agilidade',
    'proeficiencia': 'Proeficiência',
    'equilibrio': 'Equilibrio',
    'foco': 'Foco',
    'reflexos': 'Reflexos',
    'intelecto': 'Intelecto',
    'conhecimentos': 'Conhecimentos',
    'raclogico': 'Raciocinio Lógico',
    'controleemocional': 'Controle Emocional',
    'curiosidade': 'Curiosidade',
    'inspecao': 'Inspeção',
    'sabedoria': 'Sabedoria',
    'interpretacao': 'Interpretação',
    'percepcao': 'Percepção',
    'tino': 'Tino',
    'intuicao': 'Intuição',
    'empatia': 'Empatia',
    'carisma': 'Carisma',
    'aparencia': 'Aparência',
    'simpatia': 'Simpatia',
    'socializacao': 'Socialização',
    'blefe': 'Blefe',
    'ego': 'Ego',
    'sobrenatural': 'Sobrenatural',
    'religiao': 'Religião',
    'mediunidade': 'Mediunidade',
    'conhecocult': 'Conhecimento do oculto',
    'forcmental': 'Força Mental',
    'clarividencia': 'Clarividência'
}

tabela_individualizacao = {
    'forca': {
        'agressividade': {
            '1': [('brutalidade', -2), ('luta', -2), ('controleemocional', 2)],
            '2': [('brutalidade', -2), ('luta', -2), ('controleemocional', 2)],
            '3': [('brutalidade', -1), ('luta', -1), ('controleemocional', 1)],
            '4': [('brutalidade', -1), ('luta', -1), ('controleemocional', 1)],
            '5': [],
            '6': [('brutalidade', 1), ('luta', 1), ('controleemocional', -1)],
            '7': [('brutalidade', 1), ('luta', 1), ('controleemocional', -1)],
            '8': [('brutalidade', 2), ('luta', 2), ('controleemocional', -2)],
            '9': [('brutalidade', 2), ('luta', 2), ('controleemocional', -2)],
            '10': [('brutalidade', 3), ('luta', 3), ('controleemocional', -3)]
        },
        'luta': {
            '1': [('brutalidade', -2), ('equilibrio', -2)],
            '2': [('brutalidade', -2), ('equilibrio', -2)],
            '3': [('brutalidade', -1), ('equilibrio', -1)],
            '4': [('brutalidade', -1), ('equilibrio', -1)],
            '5': [],
            '6': [('brutalidade', 1), ('equilibrio', 1)],
            '7': [('brutalidade', 1), ('equilibrio', 1)],
            '8': [('brutalidade', 2), ('equilibrio', 2)],
            '9': [('brutalidade', 2), ('equilibrio', 2)],
            '10': [('brutalidade', 3), ('equilibrio', 3)]
        },
        'resistencia': {
            '1': [('brutalidade', -2)],
            '2': [('brutalidade', -2)],
            '3': [('brutalidade', -1)],
            '4': [('brutalidade', -1)],
            '5': [],
            '6': [('vigor', 1), ('foco', 1)],
            '7': [('vigor', 1), ('foco', 1)],
            '8': [('vigor', 2), ('foco', 2)],
            '9': [('vigor', 2), ('foco', 2)],
            '10': [('vigor', 3), ('foco', 3)]
        },
        'vigor': {
            '1':  [('agilidade', -2), ('equilibrio', -2)],
            '2': [('agilidade', -2), ('equilibrio', -2)],
            '3': [('agilidade', -1), ('equilibrio', -1)],
            '4': [('agilidade', -1), ('equilibrio', -1)],
            '5': [],
            '6': [('agilidade', 1), ('equilibrio', 1)],
            '7': [('agilidade', 2), ('equilibrio', 1)],
            '8': [('agilidade', 2), ('equilibrio', 2)],
            '9': [('agilidade', 2), ('equilibrio', 2)],
            '10': [('agilidade', 3), ('equilibrio', 3)],
        },
        'brutalidade': {
            '1': [],
            '2': [],
            '3': [],
            '4': [],
            '5': [],
            '6': [],
            '7': [],
            '8': [],
            '9': [],
            '10': []
        },
    },
    'destreza': {
        'agilidade': {
            '1': [('vigor', -2), ('reflexo', -2)],
            '2': [('vigor', -2), ('reflexo', -2)],
            '3': [('vigor', -1), ('reflexo', -1)],
            '4': [('vigor', -1), ('reflexo', -1)],
            '5': [],
            '6': [('vigor', 1), ('reflexo', 1)],
            '7': [('vigor', 1), ('reflexo', 1)],
            '8': [('vigor', 2), ('reflexo', 2)],
            '9': [('vigor', 2), ('reflexo', 2)],
            '10': [('vigor', 3), ('reflexo', 3)]
        },
        'proeficiencia': {
            '1': [('conhecimentos', -2), ('raclogico', -2)],
            '2': [('conhecimentos', -2), ('raclogico', -2)],
            '3': [('conhecimentos', -1), ('raclogico', -1)],
            '4': [('conhecimentos', -1), ('raclogico', -1)],
            '5': [],
            '6': [('conhecimentos', 1), ('raclogico', 1), ('foco', 1)],
            '7': [('conhecimentos', 1), ('raclogico', 1), ('foco', 1)],
            '8': [('conhecimentos', 2), ('raclogico', 2), ('foco', 2)],
            '9': [('conhecimentos', 2), ('raclogico', 2), ('foco', 2)],
            '10': [('conhecimentos', 3), ('raclogico', 3), ('foco', 3)]
        },
        'foco': {
            '1': [('intuicao', -2), ('interpretacao', -2)],
            '2': [('intuicao', -2), ('interpretacao', -2)],
            '3': [('intuicao', -1), ('interpretacao', -1)],
            '4': [('intuicao', -1), ('interpretacao', -1)],
            '5': [],
            '6': [('intuicao', 1), ('interpretacao', 1)],
            '7': [('intuicao', 1), ('interpretacao', 1)],
            '8': [('intuicao', 2), ('interpretacao', 2)],
            '9': [('intuicao', 2), ('interpretacao', 2)],
            '10': [('intuicao', 3), ('interpretacao', 3)]
        },
        'equilibrio': {
            '1': [('luta', -2), ('vigor', -2)],
            '2': [('luta', -2), ('vigor', -2)],
            '3': [('luta', -1), ('vigor', -1)],
            '4': [('luta', -1), ('vigor', -1)],
            '5': [],
            '6': [('luta', 1), ('vigor', 1)],
            '7': [('luta', 1), ('vigor', 1)],
            '8': [('luta', 2), ('vigor', 2)],
            '9': [('luta', 2), ('vigor', 2)],
            '10': [('luta', 3), ('vigor', 3)],
        },
        'reflexos': {
            '1': [('tino', -2), ('percepcao', -2)],
            '2': [('tino', -2), ('percepcao', -2)],
            '3': [('tino', -1), ('percepcao', -1)],
            '4': [('tino', -1), ('percepcao', -1)],
            '5': [],
            '6': [('tino', 1), ('percepcao', 1)],
            '7': [('tino', 1), ('percepcao', 1)],
            '8': [('tino', 2), ('percepcao', 2)],
            '9': [('tino', 2), ('percepcao', 2)],
            '10': [('tino', 3), ('percepcao', 3)]
        }
    },
    'intelecto': {
        'conhecimentos': {
            '1': [('controleemocional', -2), ('raclogico', -2), ('foco', -2)],
            '2': [('controleemocional', -2), ('raclogico', -2), ('foco', -2)],
            '3': [('controleemocional', -1), ('raclogico', -1), ('foco', -1)],
            '4': [('controleemocional', -1), ('raclogico', -1), ('foco', -1)],
            '5': [],
            '6': [('proeficiencia', 1), ('foco', 1), ('inspecao', 1)],
            '7': [('proeficiencia', 1), ('foco', 1), ('inspecao', 1)],
            '8': [('proeficiencia', 2), ('foco', 2), ('inspecao', 2)],
            '9': [('proeficiencia', 2), ('foco', 2), ('inspecao', 2)],
            '10': [('proeficiencia', 3), ('foco', 3), ('inspecao', 3)]
        },
        'raclogico': {
            '1': [('percepcao', -2), ('interpretacao', -2)],
            '2': [('percepcao', -2), ('interpretacao', -2)],
            '3': [('percepcao', -1), ('interpretacao', -1)],
            '4': [('percepcao', -1), ('interpretacao', -1)],
            '5': [],
            '6': [('percepcao', 1), ('interpretacao', 1)],
            '7': [('percepcao', 1), ('interpretacao', 1)],
            '8': [('percepcao', 2), ('interpretacao', 2)],
            '9': [('percepcao', 2), ('interpretacao', 2)],
            '10': [('percepcao', 3), ('interpretacao', 3)]
        },
        'controleemocional': {
            '1': [('agressividade', -2), ('interpretacao', -2), ('forcmental', -2)],
            '2': [('agressividade', -2), ('interpretacao', -2), ('forcmental', -2)],
            '3': [('agressividade', -1), ('interpretacao', -1), ('forcmental', -1)],
            '4': [('agressividade', -1), ('interpretacao', -1), ('forcmental', -1)],
            '5': [],
            '6': [('agressividade', -1), ('interpretacao', 1), ('forcmental', 1)],
            '7': [('agressividade', -1), ('interpretacao', 1), ('forcmental', 1)],
            '8': [('agressividade', -2), ('interpretacao', 2), ('forcmental', 2)],
            '9': [('agressividade', -2), ('interpretacao', 2), ('forcmental', 2)],
            '10': [('agressividade', -3), ('interpretacao', 3), ('forcmental', 3)],
        },
        'curiosidade': {
            '1': [('intuicao', -2), ('conhecocult', -2)],
            '2': [('intuicao', -2), ('conhecocult', -2)],
            '3': [('intuicao', -1), ('conhecocult', -1)],
            '4': [('intuicao', -1), ('conhecocult', -1)],
            '5': [],
            '6': [('intuicao', 1), ('conhecocult', 1)],
            '7': [('intuicao', 1), ('conhecocult', 1)],
            '8': [('intuicao', 2), ('conhecocult', 2)],
            '9': [('intuicao', 2), ('conhecocult', 2)],
            '10': [('intuicao', 3), ('conhecocult', 3)]
        },
        'inspecao': {
            '1': [],
            '2': [],
            '3': [],
            '4': [],
            '5': [],
            '6': [],
            '7': [],
            '8': [],
            '9': [],
            '10': []
        }
    },
    'sabedoria': {
        'interpretacao': {
            '1': [('inspecao', -2), ('conhecimento', -2), ('percepcao', -2)],
            '2': [('inspecao', -2), ('conhecimento', -2), ('percepcao', -2)],
            '3': [('inspecao', -1), ('conhecimento', -1), ('percepcao', -1)],
            '4': [('inspecao', -1), ('conhecimento', -1), ('percepcao', -1)],
            '5': [],
            '6': [('inspecao', 1), ('conhecimento', 1), ('percepcao', 1)],
            '7': [('inspecao', 1), ('conhecimento', 1), ('percepcao', 1)],
            '8': [('inspecao', 2), ('conhecimento', 2), ('percepcao', 2)],
            '9': [('inspecao', 2), ('conhecimento', 2), ('percepcao', 2)],
            '10': [('inspecao', 3), ('conhecimento', 3), ('percepcao', 3)]
        },
        'percepcao': {
            '1': [('tino', -2), ('reflexo', -2)],
            '2': [('tino', -2), ('reflexo', -2)],
            '3': [('tino', -1), ('reflexo', -1)],
            '4': [('tino', -1), ('reflexo', -1)],
            '5': [],
            '6': [('intuicao', 1), ('reflexo', 1), ('socializacao', 1)],
            '7': [('intuicao', 1), ('reflexo', 1), ('socializacao', 1)],
            '8': [('intuicao', 2), ('reflexo', 2), ('socializacao', 2)],
            '9': [('intuicao', 2), ('reflexo', 2), ('socializacao', 2)],
            '10': [('intuicao', 3), ('reflexo', 3), ('socializacao', 3)]
        },
        'tino': {
            '1': [('religiao', -2), ('mediunidade', -2), ('conhecocult', -2)],
            '2': [('religiao', -2), ('mediunidade', -2), ('conhecocult', -2)],
            '3': [('religiao', -1), ('mediunidade', -1), ('conhecocult', -1)],
            '4': [('religiao', -1), ('mediunidade', -1), ('conhecocult', -1)],
            '5': [],
            '6': [('religiao', 1), ('mediunidade', 1), ('conhecocult', 1)],
            '7': [('religiao', 1), ('mediunidade', 1), ('conhecocult', 1)],
            '8': [('religiao', 2), ('mediunidade', 2), ('conhecocult', 2)],
            '9': [('religiao', 2), ('mediunidade', 2), ('conhecocult', 2)],
            '10': [('religiao', 3), ('mediunidade', 3), ('conhecocult', 3)]
        },
        'intuicao': {
            '1': [('raclogico', -2), ('empatia', -2)],
            '2': [('raclogico', -2), ('empatia', -2)],
            '3': [('raclogico', -1), ('empatia', -1)],
            '4': [('raclogico', -1), ('empatia', -1)],
            '5': [],
            '6': [('reflexo', 1), ('empatia', 1)],
            '7': [('reflexo', 1), ('empatia', 1)],
            '8': [('reflexo', 2), ('empatia', 2)],
            '9': [('reflexo', 2), ('empatia', 2)],
            '10': [('reflexo', 3), ('empatia', 3)],
        },
        'empatia': {
            '1': [('socializacao', -2), ('simpatia', -2)],
            '2': [('socializacao', -2), ('simpatia', -2)],
            '3': [('socializacao', -1), ('simpatia', -1)],
            '4': [('socializacao', -1), ('simpatia', -1)],
            '5': [],
            '6': [('controleemocional', -1), ('simpatia', 1)],
            '7': [('controleemocional', -1), ('simpatia', 1)],
            '8': [('controleemocional', -2), ('simpatia', 2)],
            '9': [('controleemocional', -2), ('simpatia', 2)],
            '10': [('controleemocional', -3), ('simpatia', 3)]
        }
    },
    'carisma': {
        'aparencia': {
            '1': [('socializacao', -2), ('ego', -2)],
            '2': [('socializacao', -2), ('ego', -2)],
            '3': [('socializacao', -1), ('ego', -1)],
            '4': [('socializacao', -1), ('ego', -1)],
            '5': [],
            '6': [('socializacao', 1), ('ego', 1)],
            '7': [('socializacao', 1), ('ego', 1)],
            '8': [('socializacao', 2), ('ego', 2)],
            '9': [('socializacao', 2), ('ego', 2)],
            '10': [('socializacao', 3), ('ego', 3)]
        },
        'simpatia': {
            '1': [('empatia', -2), ('ego', 2)],
            '2': [('empatia', -2), ('ego', 2)],
            '3': [('empatia', -1), ('ego', 1)],
            '4': [('empatia', -1), ('ego', 1)],
            '5': [],
            '6': [('socializacao', 1), ('inspecao', 2)],
            '7': [('socializacao', 1), ('inspecao', 2)],
            '8': [('socializacao', 2), ('inspecao', 2)],
            '9': [('socializacao', 2), ('inspecao', 2)],
            '10': [('socializacao', 3), ('inspecao', 3)]
        },
        'socializacao': {
            '1': [('ego', -2), ('blefe', 2)],
            '2': [('ego', -2), ('blefe', 2)],
            '3': [('ego', -1), ('blefe', 1)],
            '4': [('ego', -1), ('blefe', 1)],
            '5': [],
            '6': [('blefe', 1), ('inspecao', 1)],
            '7': [('blefe', 1), ('inspecao', 1)],
            '8': [('blefe', 2), ('inspecao', 2)],
            '9': [('blefe', 2), ('inspecao', 2)],
            '10': [('blefe', 3), ('inspecao', 3)]
        },
        'blefe': {
            '1': [('controleemoc', -3)],
            '2': [('controleemoc', -2)],
            '3': [('controleemoc', -1)],
            '4': [('controleemoc', -1)],
            '5': [],
            '6': [('inspecao', 1)],
            '7': [('inspecao', 1)],
            '8': [('inspecao', 2)],
            '9': [('inspecao', 2)],
            '10': [('inspecao', 3)]
        },
        'ego': {
            '1': [('vigor', -2)],
            '2': [('vigor', -2)],
            '3': [('vigor', -1)],
            '4': [('vigor', -1)],
            '5': [],
            '6': [('empatia', -1)],
            '7': [('empatia', -1)],
            '8': [('empatia', -2)],
            '9': [('empatia', -2)],
            '10': [('empatia', -3)]
        },
    },
    'sobrenatural': {
        'religiao': {
            '1': [('mediunidade', -2)],
            '2': [('mediunidade', -2)],
            '3': [('mediunidade', -1)],
            '4': [('mediunidade', -1)],
            '5': [],
            '6': [('raclogico', -1), ('intuicao', 1)],
            '7': [('raclogico', -1), ('intuicao', 1)],
            '8': [('raclogico', -2), ('intuicao', 2)],
            '9': [('raclogico', -2), ('intuicao', 2)],
            '10': [('raclogico', -3), ('intuicao', 3)]
        },
        'mediunidade': {
            '1': [('clarividencia', -10)],
            '2': [('clarividencia', -5)],
            '3': [('clarividencia', -4)],
            '4': [('clarividencia', -3)],
            '5': [('clarividencia', -2)],
            '6': [('clarividencia', -1)],
            '7': [],
            '8': [('clarividencia', 1)],
            '9': [('clarividencia', 2)],
            '10': [('clarividencia', 3)]
        },
        'conhecocult': {
            '1': [('forcmental', -2)],
            '2': [('forcmental', -2)],
            '3': [('forcmental', -1)],
            '4': [('forcmental', -1)],
            '5': [],
            '6': [('forcmental', 1)],
            '7': [('forcmental', 1)],
            '8': [('forcmental', 2)],
            '9': [('forcmental', 2)],
            '10': [('forcmental', 3)]
        },
        'forcmental': {
            '1': [('controleemoc', -1)],
            '2': [('controleemoc', -1)],
            '3': [('controleemoc', -2)],
            '4': [('controleemoc', -2)],
            '5': [],
            '6': [('controleemoc', 1)],
            '7': [('controleemoc', 1)],
            '8': [('controleemoc', 2)],
            '9': [('controleemoc', 2)],
            '10': [('controleemoc', 3)]
        },
        'clarividencia': {
            '1': [],
            '2': [],
            '3': [],
            '4': [],
            '5': [],
            '6': [],
            '7': [],
            '8': [],
            '9': [],
            '10': []
        }
    }
}

tab_debuff_ficha = {
    'forca': {
        'resistencia': {
            '1': [('dano_fisico', 2)],
            '2': [('dano_fisico', 2)],
            '3': [('dano_fisico', 1)],
            '4': [('dano_fisico', 1)],
            '5': [('dano_fisico', 0)],
            '6': [('dano_fisico', 0)],
            '7': [('dano_fisico', 0)],
            '8': [('dano_fisico', 0)],
            '9': [('dano_fisico', 0)],
            '10':[('dano_fisico', 0)]
        }
    },
    'sobrenatural': {
        'forcmental': {
            '1': [('atq_insanidade', 1)],
            '2': [('atq_insanidade', 1)],
            '3': [('atq_insanidade', 2)],
            '4': [('atq_insanidade', 2)],
            '5': [('atq_insanidade', 0)],
            '6': [('atq_insanidade', 0)],
            '7': [('atq_insanidade', 0)],
            '8': [('atq_insanidade', 0)],
            '9': [('atq_insanidade', 0)],
            '10':[('atq_insanidade', 0)]
        }
    }
}

disturbios = {
    'agorafobia':[],
    'alcoolismo':[],
    'alergico':[],
    'amnesia':[],
    'anorexico':[('aparencia', -2), ('vigor', -2)],
    'ansiedade':[('controleemocional', -2), ('foco', -2)],
    'antissocial':[('aparencia', -2), ('simpatia', -2), ('socializacao', -2), ('blefe', -2), ('ego', -2)],
    'apatico':[('agressividade', -2), ('simpatia', -2)],
    'arromantico':[],
    'aspenger':[('interpretacao', -2), ('percepcao', -2), ('socializacao', -2), ('raclogico', 3), ('conhecimentos', 3)],
    'assombrado':[('mediunidade', 2), ('foco', -4)],
    'atavismo':[],
    'auto flagelacao':[('vigor', -2), ('controleemocional', -2), ('resistencia', 2)],
    'azarado':[],
    'barulhento':[('agilidade', -2), ('socializacao', -2)],
    'bestial':[('carisma', -2), ('forca', 1)],
    'caloteiro':[],
    'carente':[],
    'cegueira':[],
    'cegueira parcial':[],
    'cetico':[('religiao', -2), ('tino', -2), ('tecnologias', 2)],
    'claustrofobia':[],
    'cleptomania':[],
    'compulsao alimentar':[],
    'covardia':[],
    'culposo':[],
    'daltonismo':[],
    'deficiente - braco':[],
    'deficiente - perna':[],
    'deprimido':[('aparencia', -2), ('simpatia', -2), ('socializacao', -2), ('blefe', -2), ('ego', -2),
                 ('interpretacao', -2), ('percepcao', -2), ('tino', -2), ('intuicao', -2), ('empatia', -2)],
    'desastrado':[('equilibrio', -2)],
    'diabetico':[],
    'dislexia':[('conhecimento', -2), ('experiencia', -2)],
    'dramatico':[('controleemocional', -2), ('socializacao', 2)],
    'dsts':[('vigor', -3)],
    'egoismo':[],
    'enrustido':[],
    'eplepsia':[],
    'esquizofrenico':[('raclogico', -2), ('foco', -2)],
    'estresse crônico':[('agressividade', 1), ('vigor', -2)],
    'fanatismo':[('religiao', 1), ('raclogico', -2)],
    'fibromialgia':[('resistencia', -2), ('vigor', -1)],
    'fumante':[],
    'furia':[('raclogico', -2), ('controleemocional', -2), ('agressividade', 2)],
    'gagueira':[('socializacao', -2), ('ego', -2)],
    'hemofilia':[('resistencia', -2)],
    'hidrofobia':[],
    'hiperalgia':[('resistencia', -2),('luta', -2)],
    'hiperatividade':[('foco', -2),('proficiencia', -2)],
    'imaginativo':[('curiosidade', 2),('raclogico', -2),('percepcao', -2)],
    'infantilidade':[('socializacao', -2),('agressividade', 1)],
    'ingenuo':[],
    'labirintite':[],
    'lunático':[('raclogico', -2),('conhecimentooculto', 1)],
    'lupus':[('vigor', -2),('resistencia', -2)],
    'machista':[],
    'magreza extrema':[('forca', -2)],
    'manipulador':[],
    'mao fraca':[],
    'mau cheiro':[('aparencia', -2), ('simpatia', -2), ('socializacao', -2), ('blefe', -2), ('ego', -2)],
    'mau humorado':[],
    'medo de altura':[],
    'medo de animais':[],
    'medo do sobrenatural':[('conhecimentooculto', -2), ('tino', -2)],
    'megalomania':[('socializacao', -2), ('ego', 1)],
    'mitomania':[],
    'mudo':[('conhecimento', 2)],
    'narcisista':[('simpatia', -2), ('aparencia', 1)],
    'narcolepsia':[],
    'ninfomaniaca / satiriase':[],
    'noturno':[],
    'orgulhoso':[('ego', 1), ('simpatia', -2)],
    'paranoia':[('percepcao', -2), ('interpretacao', -2), ('tino', 2)],
    'pesadelos':[],
    'pirofobia':[],
    'piromania':[('controleemocional', -2)],
    'possuido':[],
    'preguiçoso':[('destreza', -2)],
    'psicotico':[],
    'racista':[],
    'repugnancia':[],
    'sadismo':[],
    'sangue frio':[('empatia', -2), ('tino', -1)],
    'sexista':[],
    'sobrepeso':[('destreza', -2)],
    'surdez':[('interpretacao', 2)],
    'tdah':[('foco', -2), ('percepcao', -2)],
    'tecnofobico':[],
    'teimosia':[],
    'timidez':[],
    'toc':[],
    'tourette':[('equilibrio', -2), ('socializacao', -2)],
    'trapaceiro':[],
    'traumatizado':[('controleemocional', -2), ('forcamental', 1)],
    'tremor':[('equilibrio', -2), ('foco', -2)],
    'viciado - ilicitas':[],
    'viciado em jogatina':[],
    'xenofobico':[],
    'afantasia':[('interpretacao', -2), ('tino', -1)]
}

#TODO Virtude
virtudes = {
    'abencoado':[],
    'adaptabilidade cultural':[],
    'aptidao (conhec. oculto)':[],
    'aptidao (conhecimento)':[],
    'aptidao (ferramentas)':[],
    'aptidao (magia)':[],
    'atletico':[],
    'audicao agucada':[],
    'belo/a':[],
    'boa forma':[],
    'bom senso':[],
    'carga cultural':[],
    'centro das atencões':[],
    'contatos':[],
    'corpo fechado':[],
    'empatia (animal)':[],
    'empatia (espiritos)':[],
    'empatia (pessoas)':[],
    'estudioso':[],
    'experiente':[],
    'facilidade legal':[],
    'facilidade para idiomas':[],
    'faixa branca':[],
    'filosofia':[],
    'forte':[],
    'hipoalgia':[],
    'iluminado':[],
    'indomável':[],
    'intuitivo':[],
    'leitura':[],
    'memoria eidetica':[],
    'mente de aco':[],
    'mestre em jogos':[],
    'musicista':[],
    'obstinado':[],
    'olfato agucado':[],
    'paladar agucado':[],
    'poliglota':[],
    'precognicao':[],
    'psicometria':[],
    'reconhecimento social':[],
    'reflexos apurados':[],
    'sensitivo':[],
    'senso de direcao':[],
    'sorte':[],
    'super fôlego':[],
    'talento':[],
    'toque sensivel':[],
    'vida dupla':[],
    'visao agucada':[]
}

#TODO Pericias
# pericias = {
#     '':[]
# }